<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="20015" started-at="2022-03-14T13:44:34 IST" finished-at="2022-03-14T13:44:54 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="20015" started-at="2022-03-14T13:44:34 IST" finished-at="2022-03-14T13:44:54 IST">
      <class name="testClass.TestClass">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:testClass.TestClass@1500955a]" name="launchBrowser" is-config="true" duration-ms="4864" started-at="2022-03-14T13:44:34 IST" finished-at="2022-03-14T13:44:39 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="cleatPomObjects()[pri:0, instance:testClass.TestClass@1500955a]" name="cleatPomObjects" is-config="true" duration-ms="64" started-at="2022-03-14T13:44:39 IST" finished-at="2022-03-14T13:44:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleatPomObjects -->
        <test-method status="PASS" signature="logInToApplication()[pri:0, instance:testClass.TestClass@1500955a]" name="logInToApplication" is-config="true" duration-ms="7556" started-at="2022-03-14T13:44:39 IST" finished-at="2022-03-14T13:44:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInToApplication -->
        <test-method status="FAIL" signature="testCase01()[pri:0, instance:testClass.TestClass@1500955a]" name="testCase01" duration-ms="5018" started-at="2022-03-14T13:44:47 IST" finished-at="2022-03-14T13:44:52 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at testClass.TestClass.testCase01(TestClass.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase01 -->
        <test-method status="PASS" signature="logOutFromApplication(org.testng.ITestResult)[pri:0, instance:testClass.TestClass@1500955a]" name="logOutFromApplication" is-config="true" duration-ms="2285" started-at="2022-03-14T13:44:52 IST" finished-at="2022-03-14T13:44:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase01 status=FAILURE method=TestClass.testCase01()[pri:0, instance:testClass.TestClass@1500955a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method status="PASS" signature="clearObjects()[pri:0, instance:testClass.TestClass@1500955a]" name="clearObjects" is-config="true" duration-ms="1" started-at="2022-03-14T13:44:54 IST" finished-at="2022-03-14T13:44:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearObjects -->
        <test-method status="PASS" signature="closedTheBrowser()[pri:0, instance:testClass.TestClass@1500955a]" name="closedTheBrowser" is-config="true" duration-ms="147" started-at="2022-03-14T13:44:54 IST" finished-at="2022-03-14T13:44:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedTheBrowser -->
      </class> <!-- testClass.TestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
